name: CI testing

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci_testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache the virtual environment
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: ".venv"
          key: ci-testing-${{ hashFiles('poetry.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          if [ -d ".venv" ]; then rm -rf .venv; fi
          poetry install --no-interaction --no-root -vvv --all-extras

      - name: Install project
        shell: bash
        run: poetry install --no-interaction

      - name: Run tests
        shell: bash
        run: |
          poetry run which python
          poetry run pre-commit run --all-files --verbose
