name: Build and Deploy Documentation

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  workflow_run:
    workflows:
      - "CI testing"
    types:
      - completed
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-22.04
    concurrency: ci-${{github.ref}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache the virtual environment
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: ".venv"
          key: docs-deploy-${{ hashFiles('poetry.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          if [ -d ".venv" ]; then rm -rf .venv; fi
          poetry install --no-interaction --no-root -vvv --only=docs

      - name: Install project
        shell: bash
        run: poetry install --no-interaction

      - name: Create the docs
        shell: bash
        run: poetry run make html -C docs/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html # The folder the action should deploy.
          branch: gh-pages
